name: CI Pipeline

on: push

jobs:
  tests:
    name: Test repo with mypy and pytest
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job automatically triggered by a ${{ github.event_name }} event"
          echo "Job running on a ${{ runner.os }} server"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
      - name: Install dependencies and local repo for testing
        run: |
          pip install .[test]
          pip install .
      - name: Run Tests
        run: scripts/run-tests.sh
      - if: ${{ success() }}
        run: echo "Tests successful!"

  docs:
    name: Build docs using MkDocs
    # from https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions-material-for-mkdocs
    needs:
    - tests
    runs-on: ubuntu-latest

    permissions:
      contents: write  # IMPORTANT: mandatory for pushing to gh-pages branch

    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install .[docs]
      - run: mkdocs gh-deploy --force

