name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Build docs using MkDocs
    # from https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions-material-for-mkdocs
    #needs:
    #- test
    runs-on: ubuntu-latest

    permissions:
      contents: write  # IMPORTANT: mandatory for pushing to gh-pages branch

    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install .[docs]
      - run: mkdocs gh-deploy --force

